### ISSUE TITLE
Problem with v0.12.0

### ISSUE THREAD

**Issue by liufengyun** [coursera/courseraprogramming#35]
When I used the latest `v0.12.0` to upload an image, I got following error:

```
Assembly upload complete.
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/upload.py", line 245, in command_upload
    args.grader_cpu * 1024 if hasattr(args, 'grader_cpu') else None,
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

However, if I use `v0.10.0`, there's no such problem.

**Comment by saeta** [comment]
Hi @liufengyun Thanks for reporting this. I've published `0.12.1` which merges in PR #36 So this should be fixed. Let me know if it's not. Thanks!

**Comment by liufengyun** [comment]
Thanks @saeta , it works perfectly now :+1:

**Comment by saeta** [comment]
@liufengyun great! Thanks for reporting this.
