### ISSUE TITLE
400 Client Error: Bad Request ("client is newer than server

### ISSUE THREAD

**Issue by asmod3us** [coursera/courseraprogramming#39]
Following up on #38, now getting different error in a vagrant ubuntu 14.04 box where I installed docker-engine as suggested. See below for `docker version` output. The version reported by sanity check is different than the one `docker version` lists. Any other ideas?

Error from sanity check:

```
vagrant@vagrant:/vagrant/grader$ courseraprogramming sanity
INFO:root:Checking local docker demon...
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/commands/sanity.py", line 40, in command_sanity
    docker_version = conn.version()
  File "/usr/local/lib/python2.7/dist-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 158, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 154, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.22, server API version: 1.21)")
```

 `docker version` output:

```
vagrant@vagrant:/vagrant/grader$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by saeta** [comment]
Hey @asmod3us I'm sorry you've encountered another error. :-( tl;dr: `sudo pip install docker-py==1.7.2` should fix things. (I just verified this on a fresh ubuntu machine, see below.) Once we support the latest version of docker, all of these problems should go away as well. I'm sorry it's been so difficult getting everything working. Thank you for your patience and working with us. All the best, -Brennan

``` bash
# ... install docker 1.9.1 as per https://github.com/coursera/courseraprogramming/issues/38
ubuntu@ip-10-0-9-241:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
ubuntu@ip-10-0-9-241:~$ sudo docker version
sudo: unable to resolve host ip-10-0-9-241
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
ubuntu@ip-10-0-9-241:~$ sudo pip install courseraprogramming
sudo: unable to resolve host ip-10-0-9-241
Downloading/unpacking courseraprogramming
  Downloading courseraprogramming-0.12.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/courseraprogramming/setup.py) egg_info for package courseraprogramming

Downloading/unpacking dockerfile-parse>=0.0.3 (from courseraprogramming)
  Downloading dockerfile-parse-0.0.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/dockerfile-parse/setup.py) egg_info for package dockerfile-parse

Downloading/unpacking docker-py>=1.2.3 (from courseraprogramming)
  Downloading docker_py-1.8.0-py2.py3-none-any.whl (41kB): 41kB downloaded
Downloading/unpacking requests>=2.7.0 (from courseraprogramming)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Downloading/unpacking semver>=2.2.0 (from courseraprogramming)
  Downloading semver-2.4.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/semver/setup.py) egg_info for package semver

Downloading/unpacking py2-ipaddress>=3.4.1 (from docker-py>=1.2.3->courseraprogramming)
  Downloading py2-ipaddress-3.4.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/py2-ipaddress/setup.py) egg_info for package py2-ipaddress

Downloading/unpacking websocket-client>=0.32.0 (from docker-py>=1.2.3->courseraprogramming)
  Downloading websocket_client-0.35.0.tar.gz (193kB): 193kB downloaded
  Running setup.py (path:/tmp/pip_build_root/websocket-client/setup.py) egg_info for package websocket-client

Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python2.7/dist-packages (from docker-py>=1.2.3->courseraprogramming)
Downloading/unpacking backports.ssl-match-hostname (from websocket-client>=0.32.0->docker-py>=1.2.3->courseraprogramming)
  Downloading backports.ssl_match_hostname-3.5.0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname

Installing collected packages: courseraprogramming, dockerfile-parse, docker-py, requests, semver, py2-ipaddress, websocket-client, backports.ssl-match-hostname
  Running setup.py install for courseraprogramming

    Installing courseraprogramming script to /usr/local/bin
  Running setup.py install for dockerfile-parse

  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for semver

  Running setup.py install for py2-ipaddress

  Running setup.py install for websocket-client
    changing mode of build/scripts-2.7/wsdump.py from 644 to 755

    changing mode of /usr/local/bin/wsdump.py to 755
  Running setup.py install for backports.ssl-match-hostname

Successfully installed courseraprogramming dockerfile-parse docker-py requests semver py2-ipaddress websocket-client backports.ssl-match-hostname
Cleaning up...
ubuntu@ip-10-0-9-241:~$ courseraprogramming sanity
INFO:root:Checking local docker demon...
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/commands/sanity.py", line 40, in command_sanity
    docker_version = conn.version()
  File "/usr/local/lib/python2.7/dist-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 120, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
ubuntu@ip-10-0-9-241:~$ sudo courseraprogramming sanity
sudo: unable to resolve host ip-10-0-9-241
INFO:root:Checking local docker demon...
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/commands/sanity.py", line 40, in command_sanity
    docker_version = conn.version()
  File "/usr/local/lib/python2.7/dist-packages/docker/api/daemon.py", line 78, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 158, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 154, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.22, server API version: 1.21)")
ubuntu@ip-10-0-9-241:~$ sudo pip install docker-^C
ubuntu@ip-10-0-9-241:~$ pip freeze
Cheetah==2.4.4
Landscape-Client==14.12
PAM==0.4.2
PyYAML==3.10
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
backports.ssl-match-hostname==3.5.0.1
chardet==2.0.1
cloud-init==0.7.5
colorama==0.2.5
configobj==4.7.2
courseraprogramming==0.12.1
docker-py==1.8.0
dockerfile-parse==0.0.5
html5lib==0.999
jsonpatch==1.3
jsonpointer==1.0
oauth==1.0.1
prettytable==0.7.2
py2-ipaddress==3.4.1
pyOpenSSL==0.13
pycurl==7.19.3
pyserial==2.6
python-apt==0.9.3.5ubuntu2
python-debian==0.1.21-nmu2ubuntu2
requests==2.9.1
semver==2.4.1
six==1.5.2
ssh-import-id==3.21
urllib3==1.7.1
websocket-client==0.35.0
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5
ubuntu@ip-10-0-9-241:~$ sudo pip install docker-py==1.7.2
sudo: unable to resolve host ip-10-0-9-241
Downloading/unpacking docker-py==1.7.2
  Downloading docker-py-1.7.2.tar.gz (68kB): 68kB downloaded
  Running setup.py (path:/tmp/pip_build_root/docker-py/setup.py) egg_info for package docker-py

Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.7.2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python2.7/dist-packages (from docker-py==1.7.2)
Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.7.2)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from websocket-client>=0.32.0->docker-py==1.7.2)
Installing collected packages: docker-py
  Found existing installation: docker-py 1.8.0
    Uninstalling docker-py:
      Successfully uninstalled docker-py
  Running setup.py install for docker-py

Successfully installed docker-py
Cleaning up...
ubuntu@ip-10-0-9-241:~$ sudo courseraprogramming sanity
sudo: unable to resolve host ip-10-0-9-241
INFO:root:Checking local docker demon...
INFO:root:Docker version: 1.9.1
INFO:root:Docker version ok.
INFO:root:No Dockerfile provided... skipping file checks.
ubuntu@ip-10-0-9-241:~$ 
```

**Comment by asmod3us** [comment]
Thanks, that worked!
