### ISSUE TITLE
courseraprogramming configure check-auth exception

### ISSUE THREAD

**Issue by liufengyun** [coursera/courseraprogramming#54]
`courseraprogramming configure check-auth` generates following exception:

```
ERROR:root:Encountered unexpected status code: 400 <Response [400]> {"msg":"invalid_code"}
ERROR:root:Encountered an exception during refresh token flow.
Traceback (most recent call last):
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/oauth2.py", line 417, in _exchange_refresh_tokens
    tokens = self._request_tokens_from_token_endpoint(refresh_form)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/oauth2.py", line 314, in _request_tokens_from_token_endpoint
    raise OAuth2Exception('Unexpected status code from token endpoint')
OAuth2Exception: OAuth2 Protocol Exception: Unexpected status code from token endpoint
INFO:root:Attempting to retrieve new tokens from the endpoint. You will be prompted to authorize the courseraprogramming app in your web browser.
INFO:root:About to request new OAuth2 tokens from Coursera.
Please visit the following URL to authorize this app:
    https://accounts.coursera.org/oauth2/v1/auth?access_type=offline&state=effba9c24d0143acabc24360f779b21a&redirect_uri=http%3A%2F%2Flocalhost%3A9876%2Fcallback&response_type=code&client_id=NS8qaSX18X_Eu0pyNbLsnA&scope=view_profile+manage_graders

ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/config.py", line 35, in check_auth
    auth = oauth2_instance.build_authorizer()
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/oauth2.py", line 441, in build_authorizer
    new_tokens = self._authorize_new_tokens()
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/oauth2.py", line 389, in _authorize_new_tokens
    _make_handler(state_token, code_holder))
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

The error message `Address already in use` is confusing, is something wrong here?

**Comment by liufengyun** [comment]
The problem is actually with `courseraprogramming upload` when the token expires.

If I kill all courseraprogramming processes, and run `courseraprogramming configure check-auth`, it's waiting for a browser callback, as expected.

However, when token is expired and I run `courseraprogramming upload`, there will be `Address already in use` message.

**Comment by liufengyun** [comment]
Close, the problem seems disappear.
