### ISSUE TITLE
Unable to upload docker images

### ISSUE THREAD

**Issue by liufengyun** [coursera/courseraprogramming#57]
When I try to publish new graders today, I got following exception:

```
ERROR:root:Polling API returned non-200 code. Response body: {"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/upload.py", line 224, in command_upload
    upload_information = poll_transloadit(args, upload_url)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/upload.py", line 129, in poll_transloadit
    raise Exception('Non-200 status code returned from polling API.')
Exception: Non-200 status code returned from polling API.
No handlers could be found for logger "docker.auth.auth"
```

I checked my auth status, it's OK:

```
Auth token: xxxxxx
Auth token expires in: 950.4 seconds.
Refresh token: xxxxx
```

Is the `transloadit` service down?

**Comment by liufengyun** [comment]
This is a blocker for us, though we can upload the image via web UI, we can only set memory, timeout, cpu via command line.

**Comment by saeta** [comment]
I just re-tested uploading a grader from an ubuntu EC2 instance in N.Va, and it worked appropriately. I'm not quite sure what caused your issue.

Just to check, @liufengyun what version of courseraprogramming are you using? (You can see by typing:

``` sh
$ courseraprogramming version
Your /usr/local/bin/courseraprogramming's version is:
    0.15.0
```

If you are using the latest, can you try re-uploading? (Perhaps this was a transient error with the transloadit service?)

**Comment by liufengyun** [comment]
Hi @saeta thanks for your response. My version is also `0.15.0`, and we're able to deploy two days ago. It's a little weird. I guess it might has something to do with `transloadit`. I'll retry and keep you informed.

```
dockermoocs@chara:~$ courseraprogramming version
Your /localhome/dockermoocs/bin/courseraprogramming's version is:
    0.15.0
```

**Comment by liufengyun** [comment]
It's strange, I still get the same error message. Should I reach to `transloadit`?

**Comment by saeta** [comment]
Definitely strange. You can pass the `-vvv` flag to get extra verbose output that includes the requests and responses. Could you post that here? Perhaps a clue can be found within?

**Comment by saeta** [comment]
Random question: where are you running `courseraprogramming`? (This is probably a silly idea, but I'm wondering if you're encountering a different transloadit cluster in a different AWS region.)

**Comment by liufengyun** [comment]
I'm running from a machine within EPFL. Will post the verbose output in a minute.

**Comment by liufengyun** [comment]
Following is the -vv log(`-vvv` come soon)

```
About to upload to server:
    rikki.transloadit.com
with upload id:
    851fa6d88bbb4730a7000732bca9fdd3
Status API:
    https://rikki.transloadit.com/assemblies/851fa6d88bbb4730a7000732bca9fdd3
Uploading...WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

ERROR:root:Polling API returned non-200 code. Response body: {"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/upload.py", line 212, in command_upload
    upload_information = poll_transloadit(args, upload_url)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/upload.py", line 129, in poll_transloadit
    raise Exception('Non-200 status code returned from polling API.')
Exception: Non-200 status code returned from polling API.
No handlers could be found for logger "docker.auth.auth"
DEBUG:root:Image file name: bigdata-wikipedia-babac9c.tar
DEBUG:root:Image file path: /srv/tmp/bigdata-wikipedia-babac9c.tar
Saving image bigdata-wikipedia-babac9c to /srv/tmp/bigdata-wikipedia-babac9c.tar... done.
DEBUG:root:About to read from local file cache file /localhome/dockermoocs/.coursera/oauth2_cache.pickle
DEBUG:root:Loaded from file system: {'token': u'CiAA5zLSlReD4aJSHYfajud4NsI2uwM8UB5HruA2BkZySxIlCIXYNBiBgICAECDr9pi00yoqEDUvKmkl9fF_xLtKcjWy7Jx4AA', 'expires': 1465500414.728787, 'refresh': u'huH9Nzn0ZegTY5zEe25G3oRWzvJqVdMMt7RSjlqZlgM'}
DEBUG:root:Local cache is good.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api2.transloadit.com
WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning

WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by liufengyun** [comment]
Output of `-vvv`:

```
No handlers could be found for logger "docker.auth.auth"
DEBUG:root:Image file name: bigdata-wikipedia-babac9c.tar
DEBUG:root:Image file path: /srv/tmp/bigdata-wikipedia-babac9c.tar
Saving image bigdata-wikipedia-babac9c to /srv/tmp/bigdata-wikipedia-babac9c.tar... done.
DEBUG:root:About to read from local file cache file /localhome/dockermoocs/.coursera/oauth2_cache.pickle
DEBUG:root:Loaded from file system: {'token': u'=======masked=======', 'expires': 1465500414.728787, 'refresh': u'=========masked============'}
DEBUG:root:Attempting to use a refresh token.
DEBUG:root:Posting form data {'client_secret': '===masked====', 'grant_type': 'refresh_token', 'client_id': '====masked=====', 'refresh_token': u'===masked======='} to token endpoint https://accounts.coursera.org/oauth2/v1/token
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): accounts.coursera.org
WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning

WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

DEBUG:requests.packages.urllib3.connectionpool:"POST /oauth2/v1/token HTTP/1.1" 200 None
DEBUG:root:Response from token endpoint: (200) {"access_token":"=====masked=====","expires_in":1800,"token_type":"Bearer"}
DEBUG:root:New tokens: {'token': u'=======masked=====', 'expires': 1465501921.994276, 'refresh': u'=====masked======'}
DEBUG:root:Looking to write to local authentication cache...
DEBUG:root:About to write to fs cache file: /localhome/dockermoocs/.coursera/oauth2_cache.pickle
DEBUG:root:Finished dumping cache_value to fs cache file.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api2.transloadit.com
WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

DEBUG:requests.packages.urllib3.connectionpool:"GET /instances/bored HTTP/1.1" 200 None
About to upload to server:
    rikki.transloadit.com
with upload id:
    5f1794ee85284615a14cb480e962566e
Status API:
    https://rikki.transloadit.com/assemblies/5f1794ee85284615a14cb480e962566e
Uploading...DEBUG:root:About to start the upload.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): rikki.transloadit.com
WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): rikki.transloadit.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /assemblies/5f1794ee85284615a14cb480e962566e HTTP/1.1" 404 None
WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

DEBUG:root:{"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Polling API returned non-200 code. Response body: {"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/upload.py", line 212, in command_upload
    upload_information = poll_transloadit(args, upload_url)
  File "/localhome/dockermoocs/.local/lib/python2.7/site-packages/courseraprogramming/commands/upload.py", line 129, in poll_transloadit
    raise Exception('Non-200 status code returned from polling API.')
Exception: Non-200 status code returned from polling API.
```

**Comment by saeta** [comment]
Thanks for this. It appears to be a transloadit issue, that's perhaps only affecting the EU-West region. (We're able to consistently successfully upload from US-East-1 and from Mountain View.)

I'll reach out to Transloadit presently. If possible, could you try copying your Docker image from your EPFL machine to a VM on AWS US-East-1 and see if it works properly from there?

**Comment by liufengyun** [comment]
Yes, it's most likely to be a problem of transloadit EU-West. I'll try as
you suggested and keep you updated. Thanks a lot for your help.

**Comment by saeta** [comment]
Hey @liufengyun have you been able to try in US-East-1? Does that fix the issue?

**Comment by liufengyun** [comment]
@saeta We're still in the process of getting access to machines in US-East-1. I tested this morning, the problem still persists.

BTW, do you have access to machines in EU-West? Maybe you can also check if it happens to you.

**Comment by saeta** [comment]
I just successfully uploaded from EU-Central (Frankfurt). Booting another machine in EU-West...

**Comment by liufengyun** [comment]
Thanks for your help @saeta . I'm still waiting for the access to US-East machines. I just tried again, it fails with the same error message.

From the logs, it seems that the creation of assembly is successful, but `GET /assemblies/:id` failed.

**Comment by saeta** [comment]
That's so very odd, because I just successfully uploaded from EU-West (and even got the same transloadit instance that you did).

https://rikki.transloadit.com/assemblies/455ecaab4f3c46df8d135827c5c54102

``````
ubuntu@ip-192-168-30-9:~/src/checker$ make upload
cargo build --release --target x86_64-unknown-linux-musl
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading rustc-serialize v0.3.19
 Downloading libc v0.2.11
 Downloading time v0.1.35
 Downloading get_if_addrs v0.4.0
 Downloading users v0.5.1
 Downloading typed-arena v1.2.0
 Downloading winapi v0.2.7
 Downloading kernel32-sys v0.2.2
 Downloading winapi-build v0.1.1
 Downloading c_linked_list v1.1.0
 Downloading libc v0.1.12
   Compiling winapi-build v0.1.1
   Compiling libc v0.2.11
   Compiling winapi v0.2.7
   Compiling typed-arena v1.2.0
   Compiling c_linked_list v1.1.0
   Compiling kernel32-sys v0.2.2
   Compiling libc v0.1.12
   Compiling users v0.5.1
   Compiling get_if_addrs v0.4.0
   Compiling time v0.1.35
   Compiling rustc-serialize v0.3.19
   Compiling checker v0.1.0 (file:///home/ubuntu/src/checker)
docker build -t checker .
Sending build context to Docker daemon 9.477 MB
Step 1 : FROM scratch
 ---> 
Step 2 : ADD target/x86_64-unknown-linux-musl/release/checker /
 ---> 9e93b781437d
Removing intermediate container 1bdf138f62b9
Step 3 : ADD etc/passwd /etc/passwd
 ---> a50ab9110d5b
Removing intermediate container f9d92ccbb5e1
Step 4 : ENTRYPOINT /checker
 ---> Running in 975b1d423b18
 ---> c355a5d06681
Removing intermediate container 975b1d423b18
Successfully built c355a5d06681
courseraprogramming upload checker l7E-pgWKEea0awpRLFYEEQ sRQgs 8XjJj
Saving image checker to /tmp/checker.tar... done.

About to upload to server:
    rikki.transloadit.com
with upload id:
    455ecaab4f3c46df8d135827c5c54102
Status API:
    https://rikki.transloadit.com/assemblies/455ecaab4f3c46df8d135827c5c54102

Assembly upload complete.

INFO:root:The grader status API is at: /api/gridExecutorCreationAttempts.v1/l7E-pgWKEea0awpRLFYEEQ~S3zaxnrXQIaM0ooT3ZXOBA

INFO:root:Successfully updated assignment part 8XjJj to new executor S3zaxnrXQIaM0ooT3ZXOBA```
``````

**Comment by liufengyun** [comment]
Does it have something to do with file size? In our case, the grader is about 2.7 G.

**Comment by saeta** [comment]
I'm sorry to say that I'm at a bit of a loss as to what's going on. As far as I know, you are the only one encountering this issue. @liufengyun this is perhaps a silly idea, but would you like to send me your public ssh key and I'll add them to a VM I have up, and we can try that?

**Comment by saeta** [comment]
File size is definitely perhaps an issue... Let me check to see if we've defined any limits. (2GB sounds suspicious...)

**Comment by liufengyun** [comment]
@saeta thanks, my key is here: https://github.com/liufengyun.keys

**Comment by saeta** [comment]
Hmmm, our transloadit template doesn't have anything limiting about 2GB:

`{
  "steps": {
    "export": {
      "robot": "/s3/store",
      "bucket": "...",
      "path": "authoring/programming/grid/_${fields.courseId}/${assembly.id}/${file.url_name}",
      "acl": "private"
    }
  }
}`

**Comment by saeta** [comment]
@liufengyun `ssh ubuntu@54.194.230.216`

**Comment by saeta** [comment]
Ah: this seems suspicious: http://support.transloadit.com/discussions/questions/32-is-there-a-max-upload-size

**Comment by liufengyun** [comment]
But when I upload via web, it also gets uploaded to transloadit, no?

**Comment by saeta** [comment]
That's an excellent point.

**Comment by liufengyun** [comment]
@saeta Can you check my command history. Upload runs into an exception. I got to pick up my kid now, I'll continue to investigate in ~1 hour.

**Comment by liufengyun** [comment]
Got following exception, @saeta any ideas?

```
ubuntu@ip-192-168-30-9:~$ courseraprogramming -vvv upload  --grading-timeout 1200 --grader-memory-limit 2048 --grader-cpu 2 bigdata-wikipedia-babac9c e8VseYIYEeWxQQoymFg8zQ QcWcs 5komc
No handlers could be found for logger "docker.auth.auth"
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/commands/upload.py", line 177, in command_upload
    image = get_container_image(args, d)
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/commands/upload.py", line 53, in get_container_image
    image = d.get_image(args.imageId)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/image.py", line 17, in get_image
    res = self._get(self._url("/images/{0}/get", image), stream=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 120, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by saeta** [comment]
@liufengyun looks like it couldn't export the container image from docker fast enough. I think there's a timeout flag... gimme a quick sec to look.

**Comment by saeta** [comment]
Yeah, use the `--timeout` flag.

`--timeout TIMEOUT     Set the default timeout when interacting with the
                        docker demon`

**Comment by saeta** [comment]
(Note: it should be: `courseraprogramming -vvv --timeout 120 upload --grading-timeout 1200 --grader-memory-limit 2048 --grader-cpu 2 bigdata-wikipedia-babac9c e8VseYIYEeWxQQoymFg8zQ QcWcs 5komc`)

**Comment by liufengyun** [comment]
Thanks @saeta , tying  again now.

**Comment by saeta** [comment]
@liufengyun if we can't get the upload to work via transloadit, I have some thoughts as to a potential workaround. (In short, I can push the tar file into the right S3 bucket bypassing transloadit, and then can ping the registration API.) Let me know if it fails again.

**Comment by liufengyun** [comment]
@saeta If you can just help set the parameters `--grading-timeout 1200 --grader-memory-limit 2048 --grader-cpu 2` for the two graders of the spark course, that would enable me to do further testing of the spark grading.

**Comment by liufengyun** [comment]
`--timeout 360` generates following exception, now I'm trying `480`

```
ubuntu@ip-192-168-30-9:~$ courseraprogramming -vvv --timeout 360 upload --grading-timeout 1200 --grader-memory-limit 2048 --grader-cpu 2 bigdata-wikipedia-babac9c e8VseYIYEeWxQQoymFg8zQ QcWcs 5komc
No handlers could be found for logger "docker.auth.auth"
DEBUG:root:Image file name: bigdata-wikipedia-babac9c.tar
DEBUG:root:Image file path: /tmp/bigdata-wikipedia-babac9c.tar
Saving image bigdata-wikipedia-babac9c to /tmp/bigdata-wikipedia-babac9c.tar...ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/main.py", line 96, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/commands/upload.py", line 177, in command_upload
    image = get_container_image(args, d)
  File "/usr/local/lib/python2.7/dist-packages/courseraprogramming/commands/upload.py", line 67, in get_container_image
    image_tar.write(image.data)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 166, in data
    return self.read(cache_content=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 306, in read
    data = self._fp.read()
  File "/usr/lib/python2.7/httplib.py", line 549, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 641, in _read_chunked
    return ''.join(value)
MemoryError
```

**Comment by saeta** [comment]
Ah, I think the VM we're using doesn't have enough RAM. The docker python client is silly in that it buffers everything in RAM.

**Comment by saeta** [comment]
Let me try and do the workaround I mentioned previously.

**Comment by saeta** [comment]
@liufengyun I've re-registered the previously uploaded `bigdata-example-728a394.tar` grader with the increased resource allocations.

**Comment by liufengyun** [comment]
@saeta thanks a lot. Could you please do it for `bigdata-stackoverflow-babac9c.tar` and `bigdata-wikipedia-babac9c.tar`? That would provide me enough playground to test the spark grading.

**Comment by saeta** [comment]
```
saeta@ip-10-159-119-245 ~% curl -H "===REDACTED AUTH===" "http://===REDACTED IP===/api/gridExecutorCreationAttempts.v1?q=listByCourse&courseId=e8VseYIYEeWxQQoymFg8zQ" | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2064  100  2064    0     0  31154      0 --:--:-- --:--:-- --:--:-- 31753
{
    "elements": [
        {
            "branchId": "e8VseYIYEeWxQQoymFg8zQ", 
            "bucket": "coursera-uploads", 
            "courseId": "e8VseYIYEeWxQQoymFg8zQ", 
            "executorId": "MVs5JyvLT5iZgWPHZvLa-A", 
            "filename": "bigdata-example-728a394.tar", 
            "id": "e8VseYIYEeWxQQoymFg8zQ~MVs5JyvLT5iZgWPHZvLa-A", 
            "key": "authoring/programming/grid/_/3cb81cefe70647398c2a424c9b1f8599/bigdata-example-728a394.tar", 
            "status": "COMPLETED", 
            "uploadedAt": 1465578185745, 
            "uploadedBy": 1225
        }, 
        {
            "branchId": "e8VseYIYEeWxQQoymFg8zQ", 
            "bucket": "coursera-uploads", 
            "courseId": "e8VseYIYEeWxQQoymFg8zQ", 
            "executorId": "Kvns6O3tQLuk5tABzOJWkA", 
            "filename": "bigdata-example-728a394.tar", 
            "id": "e8VseYIYEeWxQQoymFg8zQ~Kvns6O3tQLuk5tABzOJWkA", 
            "key": "authoring/programming/grid/_/3cb81cefe70647398c2a424c9b1f8599/bigdata-example-728a394.tar", 
            "status": "COMPLETED", 
            "uploadedAt": 1464688270815, 
            "uploadedBy": 863237
        }, 
        {
            "branchId": "e8VseYIYEeWxQQoymFg8zQ", 
            "bucket": "coursera-uploads", 
            "courseId": "e8VseYIYEeWxQQoymFg8zQ", 
            "executorId": "QHR4qsfTTbaWncnqtSoVTQ", 
            "filename": "bigdata-stackoverflow-babac9c.tar", 
            "id": "e8VseYIYEeWxQQoymFg8zQ~QHR4qsfTTbaWncnqtSoVTQ", 
            "key": "authoring/programming/grid/_/c6675aec099d8afa818254ebfb9c6dc8/bigdata-stackoverflow-babac9c.tar", 
            "status": "COMPLETED", 
            "uploadedAt": 1465475806116, 
            "uploadedBy": 863237
        }, 
        {
            "branchId": "e8VseYIYEeWxQQoymFg8zQ", 
            "bucket": "coursera-uploads", 
            "courseId": "e8VseYIYEeWxQQoymFg8zQ", 
            "executorId": "2OcHE_4gT7qqdmtJS8_ecQ", 
            "filename": "bigdata-wikipedia-babac9c.tar", 
            "id": "e8VseYIYEeWxQQoymFg8zQ~2OcHE_4gT7qqdmtJS8_ecQ", 
            "key": "authoring/programming/grid/_/0ea36240c59a4ef0ca35921276adfe69/bigdata-wikipedia-babac9c.tar", 
            "status": "COMPLETED", 
            "uploadedAt": 1465478262447, 
            "uploadedBy": 863237
        }, 
        {
            "branchId": "e8VseYIYEeWxQQoymFg8zQ", 
            "bucket": "coursera-uploads", 
            "courseId": "e8VseYIYEeWxQQoymFg8zQ", 
            "executorId": "QxJMdSC2TTO8E_6agNLLWw", 
            "filename": "bigdata-stackoverflow-babac9c.tar", 
            "id": "e8VseYIYEeWxQQoymFg8zQ~QxJMdSC2TTO8E_6agNLLWw", 
            "key": "authoring/programming/grid/_/c6675aec099d8afa818254ebfb9c6dc8/bigdata-stackoverflow-babac9c.tar", 
            "status": "PENDING", 
            "uploadedAt": 1465578791768, 
            "uploadedBy": 1225
        }
    ], 
    "linked": null, 
    "paging": null
}
```

The 2 with `uploadedBy: 1225` are me. Once the 2nd one exits the pending stage, you should be good to go. (Note: you still have to update the authoring interface to use the newly re-registered graders. You can differentiate based on "creation time" (aka `uploadedAt`).)

**Comment by liufengyun** [comment]
OK, @saeta thanks a lot for your help. Have a nice weekend.

**Comment by saeta** [comment]
As it turns out, I realized that you can actually call the API I used to register your graders yourself. While we'll definitely be working as quickly as we can to fix this issue so that you can use `courseraprogramming` to manage everything, perhaps this can be a workaround if you need to update the graders and I am not available.

The hypothetical workflow would be:
1. Upload graders using the web UI.
2. Make a `register_request` (https://github.com/coursera/courseraprogramming/blob/master/courseraprogramming/commands/upload.py#L244-L251) to the API endpoint (https://github.com/coursera/courseraprogramming/blob/master/courseraprogramming/commands/upload.py#L415)
3. Update the web authoring interface to use the new updated executor.

You can either load up the python source for the `courseraprogramming` tool, or alternatively, you can use [Postman](https://www.getpostman.com/) (+ [Postman Interceptor](http://blog.getpostman.com/2014/11/28/using-the-interceptor-to-read-and-write-cookies/)) to use your browser's cookie-based auth (which might be easier than using the OAuth2 authentication method).

That said, I will try and be available as often as possible to update the graders if that's easier.

I'll follow up when I know more vis-a-vis the transloadit issue.

**Comment by saeta** [comment]
Note: you can use the following link to get access to the registered graders in API form: [`https://api.coursera.org/api/gridExecutorCreationAttempts.v1?q=listByCourse&courseId=e8VseYIYEeWxQQoymFg8zQ`](https://api.coursera.org/api/gridExecutorCreationAttempts.v1?q=listByCourse&courseId=e8VseYIYEeWxQQoymFg8zQ) ([JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) makes viewing it in the browser not too bad.)

**Comment by nrhodes** [comment]
One of my teammates is getting the same ASSEMBLY_NOT_FOUND error.

He runs:

```
courseraprogramming --verbose upload grader nA4RUW01EeW8nRIpKnwp7Q --file-name 201608121652 b66y2 quL9g --additional_item_and_part b66y2 jAJFa --additional_item_and_part b66y2 CXE8T --additional_item_and_part b66y2 h2dvv --additional_item_and_part b66y2 OwvGI --additional_item_and_part d5xfz x5L7w --additional_item_and_part ZtG0y glHBa --additional_item_and_part b66y2 XxYMj --additional_item_and_part kAiGl mhA3k --additional_item_and_part kAiGl WZN6z --additional_item_and_part ekN4T FG5En --additional_item_and_part ekN4T NsVI0 --additional_item_and_part ekN4T BD1wn --additional_item_and_part kAiGl rWxJ9 --additional_item_and_part ekN4T 9lslB --additional_item_and_part w9YDz WLoJt --additional_item_and_part w9YDz 94JPH --additional_item_and_part w9YDz bCNZa --additional_item_and_part w9YDz ylPqt --additional_item_and_part b66y2 vjx9u --additional_item_and_part w9YDz m4wB9 --additional_item_and_part ekN4T 3TTZL --additional_item_and_part kAiGl weBkA --additional_item_and_part kAiGl 6AQ0N --additional_item_and_part kAiGl 6DERm --additional_item_and_part kAiGl a6Qon --additional_item_and_part w9YDz KrgP1
```

and gets the following output:

```
No handlers could be found for logger "docker.auth.auth"
DEBUG:root:Image file name: 201608121652.tar
DEBUG:root:Image file path: /tmp/201608121652.tar
Saving image grader to /tmp/201608121652.tar... done.
DEBUG:root:About to read from local file cache file /Users/alexanderskulikov/.coursera/oauth2_cache.pickle
DEBUG:root:Loaded from file system: {'token': u'CiAm4-FJ0X98OzlR2wD5N9_a-5akgM_mrtinrEJY98sVqxIlCOWoBRiBgICAECC2nI_95yoqEDUvKmkl9fF_xLtKcjWy7Jx4AA', 'expires': 1471022056.894107, 'refresh': u'fKVqk22D-by0IzWGazS1_P2YlpKYXEdnf_nR4Xqczqk'}
DEBUG:root:Local cache is good.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api2.transloadit.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /instances/bored HTTP/1.1" 200 91
About to upload to server:
machaela.transloadit.com
with upload id:
f8c0b84f6f274782a19ee53b878c1eba
Status API:
https://machaela.transloadit.com/assemblies/f8c0b84f6f274782a19ee53b878c1eba
Uploading...DEBUG:root:About to start the upload.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): machaela.transloadit.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /assemblies/f8c0b84f6f274782a19ee53b878c1eba HTTP/1.1" 404 None
DEBUG:root:{"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Polling API returned non-200 code. Response body: {"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/courseraprogramming/main.py", line 93, in main
    return args.func(args)
  File "/Library/Python/2.7/site-packages/courseraprogramming/commands/upload.py", line 212, in command_upload
    upload_information = poll_transloadit(args, upload_url)
  File "/Library/Python/2.7/site-packages/courseraprogramming/commands/upload.py", line 129, in poll_transloadit
    raise Exception('Non-200 status code returned from polling API.')
Exception: Non-200 status code returned from polling API.
cmd status of uploading:  256
FAILURE
```

**Comment by ngarg-coursera** [comment]
@liufengyun Restarting this thread since I started looking at this issue recently.

I tried to reproduce the issue, I downloaded one of the grader images from your course (bigdata-stackoverflow-babac9c.tar uploaded on Jun 10th - 2.8 GB) and tried uploading it with the same command you used the last time using a timeout of 480:

courseraprogramming -vvv --timeout 480 upload --grading-timeout 1200 --grader-memory-limit 2048 --grader-cpu 2 bigdata-stackoverflow-babac9c e8VseYIYEeWxQQoymFg8zQ QcWcs 5komc
(I've reverted any draft changes to these assignments, but you can look at the uploaded grader at https://www.coursera.org/teach/big-data-analysys/author/assets)

I was able to successfully upload it without getting the 'Memory error'. It seems like the issue is the lessor memory on the machine you're using to upload.

I'm sure there are some optimizations we can make to reduce the RAM requirements, but I think that'll always be the bottleneck as graders grow larger, what I'd advise is for you to try out a machine with higher RAM (I used a Mac with 16 GB) for further uploads.

Please let me know if the above is helpful and if it resolves the issue.

**Comment by liufengyun** [comment]
Thanks @ngarg-coursera , we recently reduced the image size (<2G) and it works now.

BTW, the error I get is as follows, it seems more likely to be a transloadit issue:

```
DEBUG:root:{"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Polling API returned non-200 code. Response body: {"error":"ASSEMBLY_NOT_FOUND","message":"The assembly you requested crashed or does not exist."}
ERROR:root:Problem when running command. Sorry!
```

Seems we are not the only one who encountered this problem: [another example](#issuecomment-239589874). I know this can be tricky, anyway we don't care about this anymore, hope it's the same case for you :)

**Comment by ngarg-coursera** [comment]
@liufengyun Good to know. I think the big image size is quite flaky in the sense any small network error can doom the upload. I'm not sure if there are good ways to overcome this, perhaps using something like tus. Apart from that, I think the upload went fine for me after uploading the timeout and retrying once.

I'll resolve this issue with the recommendation of using larger RAM machines, retry at least once, and appending a --timeout 480 flag to the courseraprogramming upload command.
