### ISSUE TITLE
No python 3 support

### ISSUE THREAD

**Issue by cab938** [coursera/courseraprogramming#65]
I can install it with pip3, but can't run the scripts in python 3.

Traceback (most recent call last):
  File "/home/brooksch/.virtualenv/py3-jupyter/bin/courseraprogramming", line 9, in <module>
    load_entry_point('courseraprogramming==0.16.0', 'console_scripts', 'courseraprogramming')()
  File "/home/brooksch/.virtualenv/py3-jupyter/lib/python3.4/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/brooksch/.virtualenv/py3-jupyter/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2570, in load_entry_point
    return ep.load()
  File "/home/brooksch/.virtualenv/py3-jupyter/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2230, in load
    return self.resolve()
  File "/home/brooksch/.virtualenv/py3-jupyter/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2236, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/home/brooksch/.virtualenv/py3-jupyter/lib/python3.4/site-packages/courseraprogramming/main.py", line 24, in <module>
    from courseraprogramming import commands
  File "/home/brooksch/.virtualenv/py3-jupyter/lib/python3.4/site-packages/courseraprogramming/commands/**init**.py", line 16, in <module>
    from . import \*  # noqa
  File "/home/brooksch/.virtualenv/py3-jupyter/lib/python3.4/site-packages/courseraprogramming/commands/config.py", line 63
    print 'Name: %s' % name
                   ^
SyntaxError: invalid syntax

**Comment by saeta** [comment]
Thanks for reporting this @cab938 . I'm not sure when we can commit to getting python3 support, but patches are always welcome! We'll definitely keep this ticket open to track this important improvement.

**Comment by echuber2** [comment]
Why does pip install a courseraprogramming launch script that invokes Python 3 if it doesn't support Python 3?
