### ISSUE TITLE
/commands/files  bug 

### ISSUE THREAD

**Issue by HelioJimeArch** [coursera/courseraprogramming#77]
i get this  problem trying to run courseraprogramming 

ArchiCurry@AdaWorkPlace-TGQ35IA:~$ courseraprogramming --help
Traceback (most recent call last):
  File "/usr/local/bin/courseraprogramming", line 9, in <module>
    load_entry_point('courseraprogramming==0.18.0', 'console_scripts', 'courseraprogramming')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/courseraprogramming/main.py", line 24, in <module>
    from courseraprogramming import commands
  File "/usr/local/lib/python3.5/dist-packages/courseraprogramming/commands/__init__.py", line 16, in <module>
    from . import *  # noqa
  File "/usr/local/lib/python3.5/dist-packages/courseraprogramming/commands/config.py", line 63
    print 'Name: %s' % name
                   ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by sashi-coursera** [comment]
To use the latest version of courseraprogramming tool, please use these steps - https://github.com/coursera/programming-assignments-demo/tree/master/custom-graders#march-2018-alert . Please let us know if this doesn't work. Thanks.
